name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    # https://github.com/actions/virtual-environments/
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v7

      - name: 🔧 Install dependencies
        run: |
          sudo apt-get install   \
            libapp-options-perl  \
            libwww-perl          \
            libjson-xs-perl      \
            libyaml-libyaml-perl \
            libdbd-csv-perl      \
            libdbd-sqlite3-perl

      # https://github.com/marketplace/actions/setup-go-environment
      - name: 🔧 Setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'build/go.mod'
          cache-dependency-path: '**/go.sum'

      # https://github.com/marketplace/actions/run-golangci-lint
      - name: 🌡️ Lint build
        uses: golangci/golangci-lint-action@v9
        with:
          working-directory: build
          skip-cache: true  # first lint action will handle

      - name: 🍳 Build build/skus
        run: cd build && make native && ./skus --version

      # https://github.com/marketplace/actions/run-golangci-lint
      - name: 🌡️ Lint gcosts
        uses: golangci/golangci-lint-action@v9
        with:
          working-directory: gcosts
          skip-cache: true  # first lint action will handle

      - name: 🍳 Build gcosts
        run: cd gcosts && make native && ./gcosts --version

      # Test binary
      - name: 🌡️ Test gcosts
        run: cd gcosts && ./gcosts help
      - name: 🌡️ Test gcosts region
        run: cd gcosts && ./gcosts region -p ../pricing.yml
      - name: 🌡️ Test gcosts compute instance
        run: cd gcosts && ./gcosts compute instance -p ../pricing.yml
      - name: 🌡️ Test gcosts calc
        run: cd gcosts && ./gcosts calc -d ../t -p ../pricing.yml
